Vagrant.configure(2) do |config|

  config.vm.box = "<%= VmImageName %>" 
  config.vm.hostname = "<%= VmName %>"
  config.vm.network :private_network, ip: "<%= VmPrivateIp %>"
  config.vm.provider "virtualbox" do |v|
    v.memory = <%= VmMemory %>
    v.cpus = <%= VmCpus %>
  end
  config.vm.provision "chef_solo" do |chef|
    chef.cookbooks_path = "chef/cookbooks"
    chef.roles_path = "chef/roles"
    chef.add_role("<%= VmRole %>")  
    chef.environments_path = "chef/environments"
    chef.environment = "development"
  end

end
